### ISSUE TITLE
[BCdatabaser] No such file or directory

### ISSUE THREAD

**Issue by janfelix** [molbiodiv/bcdatabaser#32]
Thanks for bcdatabaser, this looks great!

When using the command line tool I get this error: _[BCdatabaser] No such file or directory_
I specify the taxon list (--taxa-list /my/path/eDNA/class_list.txt) , which works when I cat: 
$ cat /my/path/eDNA/class_list.txt
Hexanauplia
Malacostraca
Gastropoda
Polychaeta
Chaetognata

Similarly, for when I also try to define the the names.dmp from my taxdump dir (--names-dmp-path /my/path/new_taxdump/names.dmp) I get this error: _Can not open file /my/path/new_taxdump/names.dmp at /bcdatabaser/bin/../lib/BCdatabaser.pm line 89, <DATA> line 6._

However, names.dmp seems to work: 
$ head /my/path/new_taxdump/names.dmp
1       |       all     |               |       synonym |
1       |       root    |               |       scientific name |
2       |       bacteria        |       bacteria <blast2>       |       blast name      |
2       |       Bacteria        |       Bacteria <prokaryotes>  |       scientific name |

I can not figure out where the problem is, it would be great to get this to work even just without the check-tax-names option...

Thanks,

jan

**Comment by iimog** [comment]
Hi Jan, thanks for using `bcdatabaser`. We use `docker` to run `bcdatabaser` which has a lot of advantages but also some potential complications. Especially when it comes to the files. If you use the command we provide in the README, including the ` -v $PWD:/data` part, then you can use relative paths below your current working directory. However, absolute paths (starting with `/`) or relative paths above the current one (e.g. `../`) will not work because they are not mapped inside your docker container. Can you try with the files you want to use in your current folder and only providing relative paths?

**Comment by janfelix** [comment]
Thanks  a lot! It is working with the lower relative paths, somehow didn't occur to me...
