### ISSUE TITLE
Fail with long taxa-lists

### ISSUE THREAD

**Issue by BWobbii** [molbiodiv/bcdatabaser#35]
I was trying to use BC-databaser with a long taxa list (5160 Species, obtained from GBIF and prepared as suggested in now closed issue #34)

My command was

`docker run -u $UID:$GID -v $PWD:/data --rm iimog/bcdatabaser\
 --outdir coi.hym.germany.2021-03-03\
 --marker-search-string "(COI OR cytochrome oxidase subunit I OR cytochrome oxidase subunit 1)" \
 --taxonomic-range Arthropoda \
 --taxa-list  bcdatabaser_Hym_ed.txt \
 --sequence-length-filter 100:2000`

My taxa list looks like this: 
[bcdatabaser_Hym_ed.txt](https://github.com/molbiodiv/bcdatabaser/files/6083668/bcdatabaser_Hym_ed.txt)
 
 I got the following error message:
 
 `Warning: Log message argument #1 undefined at /bcdatabaser/bin/bcdatabaser.pl line 317.
 Use of uninitialized value in join or string at /usr/share/perl5/Log/Log4perl/Appender.pm line 182.
 Warning: Log message argument #1 undefined at /bcdatabaser/bin/bcdatabaser.pl line 317.
 Use of uninitialized value in join or string at /usr/share/perl5/Log/Log4perl/Appender.pm line 182.
 [03-03 14:27:30] [BCdatabaser] 
 [03-03 14:27:30] [BCdatabaser] ERROR: Run search against NCBI failed`
 
 @iimog already found out that this is what's causing the problem:
` /usr/bin/esearch: Argument list too long`

A workaround might be to split the taxa list, perform BC-databaser separately and combine the outputs, but that's a bit tedious and would mean I have 2 separate DOIs...
I could potentially also shorten the list a bit further, at least for Hymenoptera in this case. But I additionally need to include some other arthropods, too, and thus I would prefer to run bc-databaser with one long list rather than separate ones.

Could this be done somehow?

Thanks a lot in advance!

**Comment by chiras** [comment]
Hey @BWobbii 
yes, this is, as far as I know, a limitation in the API request to NCBI. The work around is, as you mentioned, to split it. What could easy your way here would be to automate it. For example, I had this case recently in preparing plant reference databases for a variety of countries (each file list in format: ```Germany.cut```, ```France.cut``` etc). This will only work on the command line, not the web tool, here in this case via docker.

*splitting*
```sh
for f in *.cut; do
  country=$(cut -d. -f1 <<< "$f")
  split -l 3000 $f $country.split.
done
```

* call bcdatabaser*

```sh
mkdir -p _splitDBs
today=$(date +'%Y-%m-%d')

for f in *.split.*; do
  country=$(cut -d. -f1 <<< "$f")
  split=$(cut -d. -f3 <<< "$f")
  docker run -u $UID:$GID -v $PWD:/data --rm iimog/bcdatabaser --outdir _splitDBs/its2.$country.$split.$today --marker-search-string "(ITS2 OR internal transcribed spacer 2)" --taxonomic-range Viridiplantae --taxa-list $f --sequences-per-taxon=9 --sequence-length-filter 100:2000 --check-tax-names --names-dmp-path /NCBI-Taxonomy/names.dmp --warn-failed-tax-names

  cat _splitDBs/its2.$country.$split.$today/sequences.tax.fa >> its2.$country.GBIF.$today.tax.fa
done
```

Maybe this helps you already? As for the Zenodo DOI: You can also upload this then yourself into Zenodo and create a single DOI. 

As an alternative: you could use Genera instead of Species. It is not a limit to number of sequences, or taxa, just the length of the request to NCBI.

**Comment by BWobbii** [comment]
Hey @chiras 
thanks a lot for your help, that worked fine!
