### ISSUE TITLE
Web Interface not available

### ISSUE THREAD

**Issue by LasKru** [molbiodiv/bcdatabaser#37]
It seems like the web interface is not available at the moment. 
I tried it on Firefox and Edge.

**Comment by iimog** [comment]
Thanks, for raising this issue. You are right. Unfortunately, due to changes in the internal network the machine that is running bcdatabaser is currently not reachable from outside our University network. I'm already working to fix this but it might still take a couple of days to resolve. I'll update this issue, once we are back online.

**Comment by LasKru** [comment]
Good to know! I don't really need it right now, i've just seen this issue by accident (clicked the wrong shortcut) and thought i'd let you know.

**Comment by iimog** [comment]
The Web Interface is finally back online (the expired certificates will be renewed, soon, as well). This took way longer than I expected. I'm quite optimistic that it will stay online for the foreseeable future, now.

**Comment by LasKru** [comment]
Perfect, thank you for fixing it. I'm closing this issue now.

**Comment by LasKru** [comment]
Perfect, thank you for fixing it. I'm closing this issue now.

**Comment by LasKru** [comment]
Perfect, thank you for fixing it. I'm closing this issue now.
